"""initial_schema

Revision ID: 192cf31d6693
Revises: 
Create Date: 2026-05-27 10:38:20.610509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192cf31d6693'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_expenses')
    op.alter_column('assets', 'asset_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('STOCK', 'FII', 'ETF', 'TREASURY', 'FIXED_INCOME', 'CRYPTO', 'INTL_STOCK', 'PENSION', 'OTHER', name='asset_type_enum'),
               existing_nullable=False)
    op.alter_column('assets', 'indexer',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('IPCA_PLUS', 'CDI', 'SELIC', 'PREFIXED', 'IGPM_PLUS', name='asset_indexer_enum'),
               existing_nullable=True)
    op.alter_column('assets', 'liquidity',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('D0', 'D1', 'D2', 'MATURITY', name='liquidity_window_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'D+2'"))
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('INCOME', 'DEBIT_EXPENSE', 'CREDIT_EXPENSE', 'INVOICE_PAYMENT', 'INVESTMENT', name='transaction_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.Enum('INCOME', 'DEBIT_EXPENSE', 'CREDIT_EXPENSE', 'INVOICE_PAYMENT', 'INVESTMENT', name='transaction_type_enum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('assets', 'liquidity',
               existing_type=sa.Enum('D0', 'D1', 'D2', 'MATURITY', name='liquidity_window_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'D+2'"))
    op.alter_column('assets', 'indexer',
               existing_type=sa.Enum('IPCA_PLUS', 'CDI', 'SELIC', 'PREFIXED', 'IGPM_PLUS', name='asset_indexer_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.Enum('STOCK', 'FII', 'ETF', 'TREASURY', 'FIXED_INCOME', 'CRYPTO', 'INTL_STOCK', 'PENSION', 'OTHER', name='asset_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_table('recurring_expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'outros'"), nullable=False),
    sa.Column('periodicity', sa.VARCHAR(length=10), nullable=False),
    sa.Column('next_due_date', sa.DATE(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_recurring_positive_amount')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
